### ISSUE TITLE
BUG: Trying to run the calculate the video background module crashes the application

### ISSUE THREAD

**Issue by manuelmanso** [UmSenhorQualquer/pythonVideoAnnotator#36]
It prints this:

Traceback (most recent call last):
  File "/home/manuel/projects/pythonVideoAnnotator/plugins/pythonvideoannotator-module-backgroundfinder/pythonvideoannotator_module_backgroundfinder/backgroundfinder_window.py", line 119, in __apply_event
    update_function 		= self.__update_image_event
  File "/home/manuel/projects/pythonVideoAnnotator/libraries/mcv-api/mcvapi/filters/background_detector.py", line 25, in __init__
    super(BackgroundDetector, self).__init__(**kwargs)
  File "/home/manuel/projects/pythonVideoAnnotator/libraries/mcv-api/mcvapi/mcvbase.py", line 13, in __init__
    self.load(kwargs)
  File "/home/manuel/projects/pythonVideoAnnotator/libraries/mcv-api/mcvapi/filters/background_detector.py", line 206, in load
    self._background                = data['_background']
KeyError: '_background'
Aborted (core dumped)

**Comment by UmSenhorQualquer** [comment]
Fixed
