### ISSUE TITLE
AttributeError: 'Object2D' object has no attribute 'idtrackerai_path'

### ISSUE THREAD

**Issue by smidm** [UmSenhorQualquer/pythonVideoAnnotator#41]
Can't save a project with a video and a single object.

Steps to reproduce:
1. open video
1. add an object
1. save project
1. error dialog appears: 'Object2D' object has no attribute 'idtrackerai_path' 

```
Traceback (most recent call last):
  File ".../pythonVideoAnnotator/base/pythonvideoannotator/pythonvideoannotator/base_module/base_io.py", line 35, in save_project
    self.save({}, project_path)
  File ".../conda/envs/python-video-annotator/lib/python3.6/site-packages/pythonvideoannotator_module_virtualobjectgenerator/module.py", line 32, in save
    data = super(Module, self).save(data, project_path)
  File ".../conda/envs/python-video-annotator/lib/python3.6/site-packages/pythonvideoannotator_module_findorientation/module.py", line 29, in save
    data = super(Module, self).save(data, project_path)
  File ".../conda/envs/python-video-annotator/lib/python3.6/site-packages/pythonvideoannotator_module_backgroundfinder/module.py", line 31, in save
    data = super(Module, self).save(data, project_path)
  File ".../conda/envs/python-video-annotator/lib/python3.6/site-packages/pythonvideoannotator_module_contoursimages/module.py", line 30, in save
    data = super(Module, self).save(data, project_path)
  File ".../conda/envs/python-video-annotator/lib/python3.6/site-packages/pythonvideoannotator_module_regionsfilter/module.py", line 45, in save
    data = super(Module, self).save(data, project_path)
  File ".../conda/envs/python-video-annotator/lib/python3.6/site-packages/pythonvideoannotator_module_tracking/module.py", line 24, in save
    data = super(Module, self).save(data, project_path)
  File ".../conda/envs/python-video-annotator/lib/python3.6/site-packages/pythonvideoannotator_module_timeline/module.py", line 65, in save
    data = super(Module,self).save(data, project_path)
  File ".../conda/envs/python-video-annotator/lib/python3.6/site-packages/pythonvideoannotator_module_deeplab/module.py", line 25, in save
    data = super(Module, self).save(data, project_path)
  File ".../pythonVideoAnnotator/base/pythonvideoannotator/pythonvideoannotator/base_module/base_io.py", line 17, in save
    self._project.save(data, project_path)
  File ".../conda/envs/python-video-annotator/lib/python3.6/site-packages/pythonvideoannotator_models_gui/models/project_gui.py", line 117, in save
    data = super(ProjectGUI, self).save(data, project_path)
  File ".../conda/envs/python-video-annotator/lib/python3.6/site-packages/pythonvideoannotator_models/models/project_io.py", line 30, in save
    data['videos'].append(video.save({}, videos_path))
  File ".../conda/envs/python-video-annotator/lib/python3.6/site-packages/pythonvideoannotator_models/models/video/video_io.py", line 26, in save
    obj.save({}, obj_path)
  File ".../conda/envs/python-video-annotator/lib/python3.6/site-packages/pythonvideoannotator_module_idtrackerai/models/video/objects/object2d/object2d_idtrackerai.py", line 6, in save
    data['idtrackerai-path'] = self.idtrackerai_path.name
AttributeError: 'Object2D' object has no attribute 'idtrackerai_path'
```

**Comment by UmSenhorQualquer** [comment]
Hi smidm, I believe you are using a old version. Can you run the next command on your terminal and send me back the version you are using?
python -c "import pkg_resources; print(pkg_resources.get_distribution('python-video-annotator').version)"

**Comment by smidm** [comment]
3.306 (sorry for thedelay, I was on vacation)
