### ISSUE TITLE
Video Annotator update failed, breaks system Python

### ISSUE THREAD

**Issue by miguelgaspar24** [UmSenhorQualquer/pythonVideoAnnotator#43]
I tried updating Python Video Annotator to the latest version, as per the prompt, and got the error below:

```
ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'c:\\users\\miguel gaspar\\appdata\\local\\programs\\python\\python36-32\\Lib\\site-packages\\matplotlib\\ft2font.cp36-win32.pyd'
Consider using the `--user` option or check the permissions.
```

Now when I try running the 'start-video-annotator' command, I get the following error:

```
Traceback (most recent call last):
  File "c:\users\miguel gaspar\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\miguel gaspar\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Miguel Gaspar\AppData\Local\Programs\Python\Python36-32\Scripts\start-video-annotator.exe\__main__.py", line 5, in <module>
  File "c:\users\miguel gaspar\appdata\local\programs\python\python36-32\lib\site-packages\pythonvideoannotator\__main__.py", line 25, in <module>
    from pythonvideoannotator.base_module import BaseModule
  File "c:\users\miguel gaspar\appdata\local\programs\python\python36-32\lib\site-packages\pythonvideoannotator\base_module.py", line 9, in <module>
    from pyforms.controls import ControlPlayer
  File "c:\users\miguel gaspar\appdata\local\programs\python\python36-32\lib\site-packages\pyforms\controls.py", line 7, in <module>
    from pyforms_gui.allcontrols import *
  File "c:\users\miguel gaspar\appdata\local\programs\python\python36-32\lib\site-packages\pyforms_gui\allcontrols.py", line 26, in <module>
    from .controls.control_matplotlib import ControlMatplotlib
  File "c:\users\miguel gaspar\appdata\local\programs\python\python36-32\lib\site-packages\pyforms_gui\controls\control_matplotlib.py", line 16, in <module>
    from matplotlib.figure import Figure
  File "c:\users\miguel gaspar\appdata\local\programs\python\python36-32\lib\site-packages\matplotlib\figure.py", line 20, in <module>
    from matplotlib import backends, docstring, projections
  File "c:\users\miguel gaspar\appdata\local\programs\python\python36-32\lib\site-packages\matplotlib\projections\__init__.py", line 1, in <module>
    from .. import axes, cbook
ImportError: cannot import name 'axes'
```

This has apparently broken something in the system-installed Python, because the same error now also appears whenever I try to run my Jupyter Notebooks, which means I am no longer able to work on this machine.

**Comment by MicBoucinha** [comment]
Hi,

We strongly recommend the use of virtual environments to reduce the possibility of this kind of errors.

From the error you presented, it mentions an access denied in the matplotlib package. If you were using Jupyter Notebooks at the same time, that could be the problem.

You can try to make sure that you don't have anything Python related running and afterwards running the update command again. If that still doesn't work, you can try to open the Command Prompt as an Admin and force the update again.

If you need the command to update PythonVideoAnnotator it is:

`pip install python-video-annotator --force-reinstall`

Let me know if that fixes the problem.

**Comment by miguelgaspar24** [comment]
Hi,
it appears that the problem was indeed trying to run the update while having a Jupyter session running.
After shutting it down and rerunning the update command everything worked.
Thanks!

**Comment by MicBoucinha** [comment]
I am glad that it worked.

Please consider the using of virtual environments in the future.
